# Generated by Django 6.0.6 on 2026-06-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('golosina', 'Golosina'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
    ]
