# Generated by Django 6.0.6 on 2026-06-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_usuario', models.CharField(max_length=40, unique=True)),
                ('correo', models.EmailField(max_length=320, unique=True)),
                ('nombre_y_apellido', models.CharField(max_length=100)),
                ('curso', models.CharField(choices=[('Preceptor', 'Preceptor'), ('Profesor', 'Profesor'), ('Directivo', 'Directivo'), ('1-1', '1-1'), ('1-2', '1-2'), ('1-3', '1-3'), ('2-1', '2-1'), ('2-2', '2-2'), ('2-3', '2-3'), ('3-1', '3-1'), ('3-2', '3-2'), ('3-3', '3-3'), ('4-1', '4-1'), ('4-2', '4-2'), ('4-3', '4-3'), ('4-4', '4-4'), ('5-1', '5-1'), ('5-2', '5-2'), ('5-3', '5-3'), ('6-1', '6-1'), ('6-2', '6-2'), ('6-3', '6-3'), ('7-1', '7-1'), ('7-2', '7-2'), ('7-3', '7-3'), ('X', 'Sin curso')], default='X', max_length=20)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
    ]
