# Generated by Django 6.0.6 on 2026-06-12 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.CharField(choices=[('Preceptor', 'Preceptor'), ('Profesor', 'Profesor'), ('Directivo', 'Directivo'), ('1-1', '1-1'), ('1-2', '1-2'), ('1-3', '1-3'), ('2-1', '2-1'), ('2-2', '2-2'), ('2-3', '2-3'), ('3-1', '3-1'), ('3-2', '3-2'), ('3-3', '3-3'), ('4-2', '4-2'), ('4-3', '4-3'), ('4-4', '4-4'), ('5-2', '5-2'), ('5-3', '5-3'), ('6-2', '6-2'), ('6-3', '6-3'), ('7-2', '7-2'), ('7-3', '7-3'), ('X', 'X')], default='X', max_length=20),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
    ]
